services:
    oneup_contao_mailchimp.listener.dca:
        class: Oneup\Contao\MailChimpBundle\EventListener\DcaListener
        public: true
        arguments:
            - '@logger'

    Oneup\Contao\MailChimpBundle\EventListener\FormSubscriptionListener:
        autoconfigure: true
        arguments:
            - '@logger'
            - '@translator'
        tags:
            - { name: contao.callback, table: tl_form, target: fields.mailchimpGroups.options, method: onMailchimpGroupsOptionsCallback }
            - { name: contao.callback, table: tl_form, target: fields.mailchimpMergeTags.save, method: onMailchimpMergeTagsSaveCallback }
            - { name: contao.hook, hook: processFormData }
