services:
    oneup_contao_mailchimp.listener.dca:
        class: Oneup\Contao\MailChimpBundle\EventListener\DcaListener
        public: true

    Oneup\Contao\MailChimpBundle\EventListener\FormSubscriptionListener:
        autoconfigure: true
        arguments:
            - '@logger'
            - '@translator'
